safe:        false
auto:        true
server:      false
baseurl:    
url: http://sysfera.github.com

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
coderay:
  coderay_wrap: div
  coderay_line_numbers: inline
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: style

JB :
  sharing :
    provider : all
    twitter :
      size :
      via : SysFera
      count :
    facebook :
      appid : 348058138624352
      layout : button_count
      font :
      faces : false
      width : 90
    googleplus :
      size : medium
      width :
      annotation : bubble
    linkedin :
      counter : right